[package]
name = "sie_generate_config"
version = "0.9.0"
edition = "2021"

[[bin]]
name = "sie_generate_config"
path = "src/bin/cli.rs"

[[bin]]
name = "sie_generate_config_gui"
path = "src/bin/gui.rs"

[[bin]]
name = "opcua_test_server"
path = "src/bin/opcua_test_server.rs"

[[bin]]
name = "opcua_client_test"
path = "src/bin/opcua_client_test.rs"

[[bin]]
name = "sie_generate_config_tui"
path = "src/bin/tui.rs"

[lib]
name = "sie_generate_config"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5.4", features = ["derive", "string"] }
roxmltree = "0.20.0"
ssh2 = "0.9.4"
chrono = { version = "0.4.34", features = ["serde"] }
dotenv = "0.15.0"
ctrlc = "3.4" 
rfd = "0.15.0"     # Native file dialogs
eframe = { version = "0.31", features = [] }  # GUI framework
ratatui = "0.29.0"  # TUI framework
crossterm = "0.28.1"  # Terminal handling
dirs = "5.0.1"  # Directory utilities
opcua = { version = "0.12.0", features = ["console-logging"] }
thiserror = "2.0.12"
log = "0.4"

[dev-dependencies]
tempfile = "3.8.0"
opcua = { version = "0.12.0", features = ["client"] }
scopeguard = "1.2.0"
insta = { version = "1.39.0", features = ["redactions"] }

[build-dependencies]
dotenv = "0.15.0"

[target.'cfg(windows)'.build-dependencies]
openssl = { version = "0.10", features = ["vendored"] }
winapi = {version = "0.3.9", features = ["winuser"]}

[profile.release]
opt-level = 'z'   # Optimize for size.
lto = true        # Enable Link Time Optimisation
codegen-units = 1 # Reduced to increase optimisations.
panic = 'abort'   # Abort on panic
strip = "symbols" # Strip symbols from binary
