/// Simplified configuration generator for WebUI
/// This avoids pulling in GUI dependencies from the main project

use std::fs;
use std::path::Path;
use thiserror::Error;

#[derive(Debug, Error)]
pub enum GeneratorError {
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),
    #[error("XML parsing error: {0}")]
    XmlParse(String),
    #[error("Configuration error: {0}")]
    Config(String),
}

pub struct SimpleConfigGenerator {
    pub namespace: String,
    pub interval_ms: u64,
    pub opcua_ip: String,
    pub opcua_username: String,
    pub opcua_password: String,
    pub output_format: OutputFormat,
}

#[derive(Debug, Clone, Copy)]
pub enum OutputFormat {
    InfluxDB,
    Prometheus,
}

impl SimpleConfigGenerator {
    pub fn new(
        namespace: String,
        interval_ms: u64,
        opcua_ip: String,
        opcua_username: String,
        opcua_password: String,
        output_format: OutputFormat,
    ) -> Self {
        Self {
            namespace,
            interval_ms,
            opcua_ip,
            opcua_username,
            opcua_password,
            output_format,
        }
    }

    /// Generate Telegraf configuration from XML files
    pub fn generate_from_files(
        &self,
        xml_files: &[impl AsRef<Path>],
        output_path: impl AsRef<Path>,
    ) -> Result<String, GeneratorError> {
        let mut config = String::new();

        // Add header
        config.push_str("# Telegraf Configuration Generated by WebUI\n");
        config.push_str(&format!("# Generated at: {}\n\n", chrono::Utc::now()));

        // Add global agent config
        config.push_str("[agent]\n");
        config.push_str(&format!("  interval = \"{}ms\"\n", self.interval_ms));
        config.push_str("  round_interval = true\n");
        config.push_str("  metric_batch_size = 1000\n");
        config.push_str("  metric_buffer_limit = 10000\n");
        config.push_str("  collection_jitter = \"0s\"\n");
        config.push_str("  flush_interval = \"10s\"\n");
        config.push_str("  flush_jitter = \"0s\"\n");
        config.push_str("  precision = \"\"\n");
        config.push_str("  hostname = \"\"\n");
        config.push_str("  omit_hostname = false\n\n");

        // Add output configuration
        match self.output_format {
            OutputFormat::InfluxDB => {
                config.push_str("[[outputs.influxdb_v2]]\n");
                config.push_str("  urls = [\"http://influxdb:8086\"]\n");
                config.push_str("  token = \"${INFLUXDB_TOKEN}\"\n");
                config.push_str("  organization = \"${INFLUXDB_ORG}\"\n");
                config.push_str("  bucket = \"${INFLUXDB_BUCKET}\"\n\n");
            }
            OutputFormat::Prometheus => {
                config.push_str("[[outputs.prometheus_client]]\n");
                config.push_str("  listen = \":9273\"\n");
                config.push_str("  metric_version = 2\n\n");
            }
        }

        // Parse XML files and generate OPC-UA input configurations
        for (idx, xml_file) in xml_files.iter().enumerate() {
            let xml_content = fs::read_to_string(xml_file)?;
            let nodes = self.parse_xml_nodes(&xml_content)?;

            if !nodes.is_empty() {
                config.push_str(&format!("# Configuration from file: {}\n", 
                    xml_file.as_ref().file_name().unwrap_or_default().to_string_lossy()));
                config.push_str("[[inputs.opcua]]\n");
                config.push_str(&format!("  name = \"{}_{}\"\n", self.namespace, idx));
                config.push_str(&format!("  endpoint = \"opc.tcp://{}:4840\"\n", self.opcua_ip));
                
                // Authentication
                if self.opcua_username.is_empty() {
                    config.push_str("  auth_method = \"Anonymous\"\n");
                } else {
                    config.push_str("  auth_method = \"UserName\"\n");
                    config.push_str(&format!("  username = \"{}\"\n", self.opcua_username));
                    config.push_str(&format!("  password = \"{}\"\n", self.opcua_password));
                }
                
                config.push_str("  security_policy = \"None\"\n");
                config.push_str("  security_mode = \"None\"\n");
                config.push_str(&format!("  request_timeout = \"{}ms\"\n", self.interval_ms * 2));
                
                // Add nodes
                config.push_str("  nodes = [\n");
                for node in &nodes {
                    config.push_str(&format!("    {{name=\"{}\", namespace=\"{}\", identifier_type=\"s\", identifier=\"{}\"}},\n",
                        node.name, node.namespace, node.identifier));
                }
                config.push_str("  ]\n\n");
            }
        }

        // Write to file
        fs::write(&output_path, &config)?;

        Ok(config)
    }

    /// Parse XML file to extract OPC-UA node information
    fn parse_xml_nodes(&self, xml_content: &str) -> Result<Vec<OpcUaNode>, GeneratorError> {
        let doc = roxmltree::Document::parse(xml_content)
            .map_err(|e| GeneratorError::XmlParse(e.to_string()))?;

        let mut nodes = Vec::new();

        // Simple XML parsing - look for common node patterns
        // This is a simplified version; the full implementation would be more sophisticated
        for node in doc.descendants() {
            if node.tag_name().name() == "UAVariable" || node.tag_name().name() == "Variable" {
                if let Some(node_id) = node.attribute("NodeId").or_else(|| node.attribute("nodeId")) {
                    let name = node.attribute("BrowseName")
                        .or_else(|| node.attribute("browseName"))
                        .unwrap_or("unknown")
                        .to_string();
                    
                    // Parse namespace and identifier from NodeId (format: ns=X;s=identifier)
                    let (namespace, identifier) = parse_node_id(node_id);
                    
                    nodes.push(OpcUaNode {
                        name,
                        namespace,
                        identifier,
                    });
                }
            }
        }

        Ok(nodes)
    }
}

#[derive(Debug)]
struct OpcUaNode {
    name: String,
    namespace: String,
    identifier: String,
}

/// Parse OPC-UA NodeId format (e.g., "ns=2;s=MyNode")
fn parse_node_id(node_id: &str) -> (String, String) {
    let parts: Vec<&str> = node_id.split(';').collect();
    let mut namespace = "0".to_string();
    let mut identifier = node_id.to_string();

    for part in parts {
        if part.starts_with("ns=") {
            namespace = part[3..].to_string();
        } else if part.starts_with("s=") || part.starts_with("i=") {
            identifier = part[2..].to_string();
        }
    }

    (namespace, identifier)
}
