FROM ubuntu:22.04

# Install required packages
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    openssh-server \
    sudo \
    wget \
    gnupg\
    apt-transport-https \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Configure SSH
RUN mkdir /run/sshd
RUN echo 'root:root' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Create test user
RUN useradd -m -s /bin/bash testuser && \
    echo 'testuser:testpass' | chpasswd && \
    echo 'testuser ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/testuser && \
    mkdir -p /home/testuser/.ssh && \
    chmod 700 /home/testuser/.ssh

# ---

# add influxdata repo
RUN wget -q https://repos.influxdata.com/influxdata-archive_compat.key
RUN echo '393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c influxdata-archive_compat.key' | sha256sum -c && cat influxdata-archive_compat.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg > /dev/null
RUN echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list

# install telegraf
RUN sudo apt-get update && sudo apt-get install telegraf
RUN sudo service telegraf start

RUN sudo apt-get install -y influxdb2
RUN sudo service influxdb start

RUN chown -R testuser:testuser /etc/telegraf && \
    chmod -R 775 /etc/telegraf && \
    usermod -aG telegraf testuser

RUN chown -R testuser:testuser /var/log/telegraf && \
    chmod -R 775 /var/log/telegraf && \
    usermod -aG telegraf testuser
# ---

# Expose SSH port
EXPOSE 22

# Start SSH service
CMD ["/usr/sbin/sshd", "-D"]
