(function() {
    'use strict';

    var DEMO_MODE = false;

    var mockSystemInfo = {
        device_name: 'SIMATIC IOT2050',
        hostname: 'iot2050-demo',
        ip_address: '192.168.1.100',
        system_time: new Date().toLocaleString(),
        utc_time: new Date().toISOString().replace('T', ' ').split('.')[0] + ' UTC',
        utc_offset: '+0100',
        architecture: 'aarch64 (ARM64)',
        uptime: '3 days, 14:22:07',
        load_average: '0.42, 0.38, 0.35',
        memory: {
            used_mb: 942,
            total_mb: 1987,
            percent: '47%'
        },
        disk: {
            used: '6.2 GB',
            total: '14 GB',
            percent: '44%'
        },
        containers_running: '5'
    };

    var mockLogs = {
        grafana: [
            't=2026-05-27T10:15:32+0200 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000',
            't=2026-05-27T10:15:32+0200 lvl=info msg="Starting Grafana" logger=server version=11.0.0',
            't=2026-05-27T10:15:33+0200 lvl=info msg="Connected to DB" logger=sqlstore db=sqlite3',
            't=2026-05-27T10:15:33+0200 lvl=info msg="Upgrading database schema" caller=sqlstore',
            't=2026-05-27T10:15:34+0200 lvl=info msg="Executing migration" logger=migration id=v1',
            't=2026-05-27T10:15:35+0200 lvl=info msg="Started background scheduler" logger=ngalert',
            't=2026-05-27T10:15:36+0200 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=https subpath=',
            't=2026-05-27T10:16:01+0200 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/health status=200',
        ].join('\n'),
        influxdb: [
            'ts=2026-05-27T10:15:30.432Z lvl=info msg="Welcome to InfluxDB" log_id=0jN2QEKW000 service=influxd version=2.7.6',
            'ts=2026-05-27T10:15:30.433Z lvl=info msg="Resources opened" log_id=0jN2QEKW000 service=storage engine=tsm1',
            'ts=2026-05-27T10:15:30.534Z lvl=info msg="Starting HTTP server" log_id=0jN2QEKW000 service=http addr=:8086',
            'ts=2026-05-27T10:15:30.535Z lvl=info msg="Starting on /usr/lib/influxdb" log_id=0jN2QEKW000',
            'ts=2026-05-27T10:15:31.100Z lvl=info msg="Ready for queries" log_id=0jN2QEKW000',
        ].join('\n'),
        telegraf: [
            '2026-05-27T10:15:28Z I! Starting Telegraf 1.31.0',
            '2026-05-27T10:15:28Z I! Loaded inputs: opcua cpu disk diskio kernel mem processes swap system',
            '2026-05-27T10:15:28Z I! Loaded outputs: influxdb_v2',
            '2026-05-27T10:15:28Z I! Tags enabled: host=iot2050-demo',
            '2026-05-27T10:15:28Z I! [agent] Config: interval:10s, quiet:false, hostname:iot2050-demo, flush_interval:10s',
            '2026-05-27T10:15:38Z I! [inputs.opcua] Connected to opc.tcp://192.168.1.10:4840',
            '2026-05-27T10:15:38Z I! [inputs.opcua] Subscribed to 24 nodes',
        ].join('\n'),
        prometheus: [
            'ts=2026-05-27T10:15:31.432Z caller=main.go:552 level=info msg="Starting Prometheus" version=2.52.0',
            'ts=2026-05-27T10:15:31.433Z caller=main.go:557 level=info msg="Build context" go=go1.22.3',
            'ts=2026-05-27T10:15:31.534Z caller=main.go:571 level=info msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml',
            'ts=2026-05-27T10:15:31.634Z caller=main.go:600 level=info msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml',
            'ts=2026-05-27T10:15:31.635Z caller=main.go:566 level=info msg="Server is ready to receive web requests."',
        ].join('\n'),
        'nginx-dashboard': [
            '2026/05/27 10:15:28 [notice] 1#1: using the "epoll" event method',
            '2026/05/27 10:15:28 [notice] 1#1: nginx/1.26.0',
            '2026/05/27 10:15:28 [notice] 1#1: built by gcc 12.2.0 (Debian 12.2.0-14)',
            '2026/05/27 10:15:28 [notice] 1#1: OS: Linux 6.1.0-rpi8',
            '2026/05/27 10:15:28 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576',
            '2026/05/27 10:15:28 [notice] 1#1: start worker processes',
            '2026/05/27 10:15:28 [notice] 1#1: start worker process 7',
            '10.0.0.1 - - [27/May/2026:10:15:58 +0200] "GET / HTTP/1.1" 200 12345',
        ].join('\n')
    };

    var mockTelegrafConfig = [
        '# Telegraf Configuration - Generated by IoT2050 Monitor',
        '#',
        '[global_tags]',
        '  host = "iot2050-demo"',
        '',
        '[agent]',
        '  interval = "10s"',
        '  round_interval = true',
        '  metric_batch_size = 1000',
        '  metric_buffer_limit = 10000',
        '  collection_jitter = "0s"',
        '  flush_interval = "10s"',
        '  flush_jitter = "0s"',
        '  debug = false',
        '  quiet = false',
        '  hostname = "iot2050-demo"',
        '',
        '[[outputs.influxdb_v2]]',
        '  urls = ["http://influxdb:8086"]',
        '  token = "${INFLUXDB_TOKEN}"',
        '  organization = "iot2050"',
        '  bucket = "telegraf"',
        '',
        '[[inputs.opcua]]',
        '  name = "plc_metrics"',
        '  endpoint = "opc.tcp://192.168.1.10:4840"',
        '  username = "${OPCUA_USERNAME}"',
        '  password = "${OPCUA_PASSWORD}"',
        '  security_policy = "None"',
        '  nodes = [',
        '    {name = "temperature", identifier = "ns=3;s=Temperature", data_type = "Float"},',
        '    {name = "pressure", identifier = "ns=3;s=Pressure", data_type = "Float"},',
        '    {name = "motor_speed", identifier = "ns=3;s=MotorSpeed", data_type = "Float"},',
        '  ]',
        '',
        '[[inputs.cpu]]',
        '[[inputs.disk]]',
        '[[inputs.mem]]',
        '[[inputs.system]]',
    ].join('\n');

    var mockPlcTime = {
        success: true,
        plc_time: '2026-05-27 10:15:30',
        plc_time_offset_ms: -12.5
    };

    var originalFetch = window.fetch;

    function mockResponse(data, status) {
        status = status || 200;
        var body = typeof data === 'string' ? data : JSON.stringify(data);
        return Promise.resolve({
            ok: status >= 200 && status < 300,
            status: status,
            statusText: status === 200 ? 'OK' : 'Error',
            json: function() { return Promise.resolve(typeof data === 'string' ? JSON.parse(data) : data); },
            text: function() { return Promise.resolve(typeof data === 'string' ? data : JSON.stringify(data)); }
        });
    }

    function handleMockFetch(url, options) {
        var path = typeof url === 'string' ? url : (url.url || '');
        path = path.replace(/^https?:\/\/[^/]+/, '');

        if (path === '/chronograf/health') {
            return mockResponse({message: 'ok'});
        }
        if (path === '/grafana/api/health') {
            return mockResponse({commit: 'abc123', database: 'ok', version: '11.0.0'});
        }
        if (path === '/influxdb/health') {
            return mockResponse({checks: [], message: 'ready for queries and writes', status: 'pass', version: '2.7.6'});
        }
        if (path === '/prometheus/-/healthy') {
            return mockResponse({status: 'success'});
        }
        if (path === '/telegraf/metrics') {
            return mockResponse('# HELP telegraf_metrics Telegraf metrics\n# TYPE telegraf_metrics counter\ntelegraf_metrics 1\n');
        }
        if (path === '/api/health') {
            return mockResponse({status: 'ok', service: 'config-generator'});
        }
        if (path === '/api/system-info') {
            mockSystemInfo.system_time = new Date().toLocaleString();
            mockSystemInfo.utc_time = new Date().toISOString().replace('T', ' ').split('.')[0] + ' UTC';
            return mockResponse(mockSystemInfo);
        }
        if (path === '/api/opcua/plc-time-stored') {
            return mockResponse(mockPlcTime);
        }
        if (path === '/api/config/telegraf') {
            return mockResponse(mockTelegrafConfig);
        }
        if (/^\/api\/containers\/([^/]+)\/logs$/.test(path)) {
            var container = path.match(/^\/api\/containers\/([^/]+)\/logs$/)[1];
            var logs = mockLogs[container] || 'No demo logs available for ' + container;
            return mockResponse(logs);
        }
        if (/^\/api\/containers\/([^/]+)\/restart$/.test(path)) {
            var match = path.match(/^\/api\/containers\/([^/]+)\/restart$/);
            return mockResponse({success: true, message: 'Container ' + match[1] + ' restarted (demo mode)'});
        }

        return originalFetch.apply(this, arguments);
    }

    function detectDemoMode() {
        var isDemo = false;

        try {
            var searchParams = new URLSearchParams(window.location.search);
            if (searchParams.get('demo') === '1') {
                isDemo = true;
            }
        } catch(e) {}

        if (window.location.protocol === 'file:') {
            isDemo = true;
        }

        if (window.DEMO_MODE === true) {
            isDemo = true;
        }

        return isDemo;
    }

    function addDemoBanner() {
        if (document.getElementById('demo-banner')) return;

        var banner = document.createElement('div');
        banner.id = 'demo-banner';
        banner.style.cssText = 'background:linear-gradient(135deg,#f59e0b,#d97706);color:white;text-align:center;padding:8px 16px;font-size:14px;font-weight:500;position:fixed;top:0;left:0;right:0;z-index:9999;box-shadow:0 2px 8px rgba(0,0,0,0.2);';
        banner.textContent = 'Demo Mode \u2014 This is a static preview with mock data. No live services are connected.';

        document.body.style.paddingTop = '40px';
        document.body.insertBefore(banner, document.body.firstChild);

        var existingBanner = document.querySelector('.demo-banner-spacer');
        if (!existingBanner) {
            var spacer = document.createElement('div');
            spacer.style.height = '40px';
            spacer.className = 'demo-banner-spacer';
            document.body.insertBefore(spacer, document.body.firstChild);
        }
    }

    function patchLinks() {
        var externalLinks = document.querySelectorAll('a[href*=":3000"], a[href*=":8888"], a[href*=":8086"], a[href*=":9090"]');
        externalLinks.forEach(function(link) {
            link.addEventListener('click', function(e) {
                e.preventDefault();
                var banner = document.getElementById('demo-banner');
                if (banner) {
                    var origText = banner.textContent;
                    banner.textContent = '\u26a0 External service links are disabled in demo mode';
                    banner.style.background = 'linear-gradient(135deg,#ef4444,#dc2626)';
                    setTimeout(function() {
                        banner.textContent = origText;
                        banner.style.background = 'linear-gradient(135deg,#f59e0b,#d97706)';
                    }, 2000);
                }
            });
        });

        var proxyLinks = document.querySelectorAll('a[href="/prometheus"], a[href="/telegraf/metrics"]');
        proxyLinks.forEach(function(link) {
            link.addEventListener('click', function(e) {
                e.preventDefault();
                var banner = document.getElementById('demo-banner');
                if (banner) {
                    var origText = banner.textContent;
                    banner.textContent = '\u26a0 External service links are disabled in demo mode';
                    banner.style.background = 'linear-gradient(135deg,#ef4444,#dc2626)';
                    setTimeout(function() {
                        banner.textContent = origText;
                        banner.style.background = 'linear-gradient(135deg,#f59e0b,#d97706)';
                    }, 2000);
                }
            });
        });
    }

    function initDemo() {
        if (!DEMO_MODE) return;

        window.fetch = function() {
            return handleMockFetch.apply(this, arguments);
        };

        if (document.readyState === 'loading') {
            document.addEventListener('DOMContentLoaded', function() {
                addDemoBanner();
                patchLinks();
            });
        } else {
            addDemoBanner();
            patchLinks();
        }
    }

    function tryAutoDetect() {
        var testUrl = '/api/health';
        originalFetch(testUrl, {method: 'GET', cache: 'no-cache'}).then(function(response) {
            if (!response.ok) {
                throw new Error('not ok');
            }
        }).catch(function() {
            DEMO_MODE = true;
            initDemo();
        });
    }

    if (detectDemoMode()) {
        DEMO_MODE = true;
        initDemo();
    } else {
        tryAutoDetect();
    }
})();