use crate::error::TelegrafError;
use roxmltree::Document;

#[derive(Clone, Copy, PartialEq, Debug)]
pub enum OutputFormat {
    InfluxDB,
    Prometheus,
}

#[derive(Clone)]
pub struct NamespaceInfo {
    pub number: String,
    pub file_name: String,
}

#[derive(Clone)]
pub struct OpcuaConfig<'a> {
    // Connection settings
    pub ip: &'a str,
    pub username: &'a str,
    pub password: &'a str,
    pub is_listener: bool,

    // Group settings
    pub group_name: &'a str,
    pub namespace_number: &'a str,
    pub interval_ms: u64,         // Store as u64 and format when needed
    pub identifier_type: &'a str, // Type of identifier: i=numeric, s=string, g=guid, b=bytestring
}

impl OpcuaConfig<'_> {
    fn get_interval_string(&self) -> String {
        format!("{}ms", self.interval_ms)
    }
}

pub fn format_config_header(
    influx_token: &str,
    bucket_name: &str,
    config_strings: &[String],
    namespace_infos: &[NamespaceInfo],
    output_format: OutputFormat,
    include_test_inputs: bool,
) -> String {
    let namespace_comments = namespace_infos
        .iter()
        .map(|ns| format!("# Namespace for file {}: {}", ns.file_name, ns.number))
        .collect::<Vec<String>>()
        .join("\n");

    let output_config = match output_format {
        OutputFormat::InfluxDB => format!(
            r#"# Configuration for sending metrics to InfluxDB 2.0
[[outputs.influxdb_v2]]
  urls = ["http://127.0.0.1:8086"]
  token = "{}"
  organization = "org"
  bucket = "{}""#,
            influx_token, bucket_name
        ),
        OutputFormat::Prometheus => r#"# Configuration for exposing Prometheus metrics
[[outputs.prometheus_client]]
  ## Address to listen on
  listen = ":9273"
  
  ## Metric version controls the mapping from Telegraf metrics to
  ## Prometheus format.  When using the prometheus input, use the same value in
  ## both plugins to ensure metrics are round-tripped without modification.
  ##
  ##   example: metric_version = 1; deprecated in favor of metric_version = 2
  ##            metric_version = 2; recommended version
  # metric_version = 1
  
  ## Use HTTP Basic Authentication.
  # basic_username = "Foo"
  # basic_password = "Bar""#
            .to_string(),
    };

    // Define test inputs if requested
    let test_inputs = if include_test_inputs {
        r#"#=================================================================================
#      (> •.•)> ⭐️ TEST INPUTS START - CPU, DISK, MEMORY - AUTOGENERATED 
#=================================================================================

[[inputs.cpu]]
  percpu = false
  totalcpu = true

[[inputs.swap]]

[[inputs.disk]]
  ## By default stats will be gathered for all mount points.
  ## Set mount_points will restrict the stats to only the specified mount points.
  # mount_points = ["/"]

  ## Ignore mount points by filesystem type.
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

[[inputs.mem]]
  # no configuration

#=================================================================================
#                          TEST INPUTS END (੭｡╹▿╹｡)੭
#=================================================================================
"#
        .to_string()
    } else {
        String::new()
    };

    format!(
        r#"{}

##################################

# Global tags can be specified here in key="value" format.
[global_tags]

# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "1000ms"
  round_interval = true

  metric_batch_size = 10000
  metric_buffer_limit = 100000

  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "0s"

  ## Log at debug level.
  # debug = false
  ## Log only error level messages.
  # quiet = false

  logfile = "/var/log/telegraf/telegraf.log"
  logfile_rotation_max_size = "25MB"
  logfile_rotation_max_archives = 4

  hostname = ""
  omit_hostname = false

{}

{}
{}
"#,
        namespace_comments,
        output_config,
        if !test_inputs.is_empty() {
            test_inputs + "\n"
        } else {
            String::new()
        },
        config_strings.join("\n\n")
    )
}

fn format_config(config: &OpcuaConfig, nodes_str: &str) -> String {
    if config.is_listener {
        format_listener_config(config, nodes_str)
    } else {
        format_regular_config(config, nodes_str)
    }
}

pub fn format_regular_config(config: &OpcuaConfig, nodes_str: &str) -> String {
    let interval = config.get_interval_string();

    format!(
        r#"
[[inputs.opcua]]
  name = "opcua"
  endpoint = "opc.tcp://{}"
  connect_timeout = "300s"
  request_timeout = "10s"
  session_timeout = "5m"
  security_policy = "Basic256Sha256"
  security_mode = "SignAndEncrypt"
  certificate = ""
  private_key = ""
  auth_method = "UserName"
  username = "{}"
  password = "{}"
  timestamp = "gather"
  client_trace = false
  interval = "{}"
    [[inputs.opcua.group]]
      name = "{}"
      namespace = "{}"
      identifier_type = "{}"
      nodes = [
        {}
      ]
    "#,
        config.ip,
        config.username,
        config.password,
        interval,
        config.group_name,
        config.namespace_number,
        config.identifier_type,
        nodes_str
    )
}

fn format_listener_config(config: &OpcuaConfig, nodes_str: &str) -> String {
    let interval = config.get_interval_string();

    format!(
        r#"
[[inputs.opcua_listener]]
  name = "opcua_listener"
  endpoint = "opc.tcp://{}"
  connect_fail_behavior = "ignore"
  connect_timeout = "300s"
  request_timeout = "10s"
  session_timeout = "20m"
  security_policy = "Basic256Sha256"
  security_mode = "SignAndEncrypt"
  certificate = ""
  private_key = ""
  auth_method = "UserName"
  username = "{}"
  password = "{}"
  timestamp = "gather"
  client_trace = false
    [[inputs.opcua_listener.group]]
      name = "{}"
      namespace = "{}"
      identifier_type = "{}"
      sampling_interval = "{}"
      nodes = [
        {}
      ]
    "#,
        config.ip,
        config.username,
        config.password,
        config.group_name,
        config.namespace_number,
        config.identifier_type,
        interval,
        nodes_str
    )
}

pub fn format_browsed_config(config: &OpcuaConfig, nodes_str: &str) -> String {
    let interval = config.get_interval_string();

    format!(
        r#"
[[inputs.opcua]]
  name = "opcua"
  endpoint = "opc.tcp://{}"
  connect_timeout = "300s"
  request_timeout = "10s"
  session_timeout = "5m"
  security_policy = "Basic256Sha256"
  security_mode = "SignAndEncrypt"
  certificate = ""
  private_key = ""
  auth_method = "UserName"
  username = "{}"
  password = "{}"
  timestamp = "gather"
  client_trace = false
  interval = "{}" 
{}
    "#,
        config.ip, config.username, config.password, interval, nodes_str
    )
}

pub fn parse_xml(
    config: &OpcuaConfig,
    xml_file: &str,
    namespace_infos: &mut Vec<NamespaceInfo>,
) -> Result<String, TelegrafError> {
    let xml = std::fs::read_to_string(xml_file).map_err(|e| TelegrafError::IoError(e))?;

    let doc = Document::parse(&xml)
        .map_err(|e| TelegrafError::ConfigError(format!("Invalid XML format: {}", e)))?;

    let file_name = std::path::Path::new(xml_file)
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("unknown")
        .to_string();

    namespace_infos.push(NamespaceInfo {
        number: config.namespace_number.to_string(),
        file_name: file_name.clone(),
    });

    let mut nodes = Vec::new();
    let mut node_names = std::collections::HashSet::new();

    let mut display_name = String::new();
    for variable in doc.descendants().filter(|n| n.has_tag_name("UAObject")) {
        let node_id = variable.attribute("NodeId");
        // Check for the specific node and print its DisplayName
        if let Some(node_id) = node_id {
            if node_id == "ns=2;i=1" {
                if let Some(found_name) = variable
                    .descendants()
                    .find(|n| n.has_tag_name("DisplayName"))
                    .and_then(|n| n.text())
                {
                    display_name = found_name.to_string();
                    println!("# BrowseName for {}: {}", file_name, found_name);
                }
            }
        }
    }
    for variable in doc.descendants().filter(|n| n.has_tag_name("UAVariable")) {
        let node_id = variable.attribute("NodeId");
        if let Some(node_id) = node_id {
            if node_id.starts_with("ns=2;i=") {
                let identifier = node_id.split('=').nth(2).unwrap().to_string();

                let mut name = variable
                    .descendants()
                    .find(|n| n.has_tag_name("BrowseName"))
                    .and_then(|n| n.text())
                    .unwrap_or_default()
                    .to_string();

                if let Some(var_mapping) = variable
                    .descendants()
                    .find(|n| n.has_tag_name("VariableMapping"))
                    .and_then(|n| n.text())
                {
                    let var_mapping = var_mapping.replace('"', "");
                    name = var_mapping;
                }

                // Check for duplicate names
                if !node_names.insert(name.clone()) {
                    return Err(TelegrafError::DuplicateNodeError(format!(
                        "Duplicate node name '{}' found in {}",
                        name, xml_file
                    )));
                }

                nodes.push(format!(
                    "{{name=\"{}\", identifier=\"{}\"}}",
                    name, identifier
                ));
            }
        }
    }

    let nodes_str = nodes.join(",\n        ");

    let group_name = if !display_name.is_empty() {
        display_name
    } else {
        //TODO: should always find one tbh
        std::path::Path::new(xml_file)
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("unknown")
            .to_string()
    };

    let config_with_group = OpcuaConfig {
        group_name: &group_name,
        ..config.clone()
    };

    Ok(format_config(&config_with_group, &nodes_str))
}
