apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      httpMode: POST
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
      tlsSkipVerify: true
      version: 'Flux'
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    version: 1
    editable: true
